"""Review store — persists recommendation review status and decision records.

Recommendations are generated by the evidence engine on every request; the
status (open/approved/dismissed) and the Decision an operator applies live here
as immutable JSON artifacts so human intent survives restarts.
"""

from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

REVIEW_DIR = "review_store"
DECISION_DIR = "review_decisions"


class ReviewStore:
    """Persists recommendation status transitions (append-only per id)."""

    def __init__(self, review_dir: str = REVIEW_DIR, decision_dir: str = DECISION_DIR):
        self._review_dir = review_dir
        self._decision_dir = decision_dir
        os.makedirs(review_dir, exist_ok=True)
        os.makedirs(decision_dir, exist_ok=True)

    # ── Recommendation review state ────────────────────────────────────

    def set_status(self, rec_id: str, status: str, notes: str = "") -> dict:
        """Record a status transition for a recommendation (idempotent by id)."""
        record = {
            "id": rec_id,
            "status": status,
            "notes": notes,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }
        path = self._review_path(rec_id)
        with open(path, "w") as f:
            json.dump(record, f, indent=2, default=str)
        return record

    def get_status(self, rec_id: str) -> Optional[dict]:
        path = self._review_path(rec_id)
        if not os.path.exists(path):
            return None
        try:
            with open(path, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return None

    def list_reviews(self) -> list[dict]:
        if not os.path.exists(self._review_dir):
            return []
        result = []
        for fname in sorted(os.listdir(self._review_dir), reverse=True):
            path = os.path.join(self._review_dir, fname)
            try:
                with open(path, "r") as f:
                    result.append(json.load(f))
            except (json.JSONDecodeError, IOError):
                continue
        return result

    # ── Decisions ──────────────────────────────────────────────────────

    def create_decision(
        self,
        rec_id: str,
        decision: str,
        reviewer_notes: str = "",
        recommendation_title: str = "",
        recommendation_type: str = "",
    ) -> dict:
        """Create an immutable Decision artifact from a human review."""
        decision_id = f"dec-{uuid.uuid4().hex[:12]}"
        record = {
            "id": decision_id,
            "recommendation_id": rec_id,
            "recommendation_type": recommendation_type,
            "recommendation_title": recommendation_title,
            "decision": decision,  # "approved" | "dismissed"
            "reviewer_notes": reviewer_notes,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        path = os.path.join(self._decision_dir, f"{decision_id}.json")
        with open(path, "w") as f:
            json.dump(record, f, indent=2, default=str)
        return record

    def list_decisions(self, limit: int = 100) -> list[dict]:
        if not os.path.exists(self._decision_dir):
            return []
        files = sorted(os.listdir(self._decision_dir), reverse=True)[:limit]
        result = []
        for fname in files:
            path = os.path.join(self._decision_dir, fname)
            try:
                with open(path, "r") as f:
                    result.append(json.load(f))
            except (json.JSONDecodeError, IOError):
                continue
        return result

    # ── Internal ───────────────────────────────────────────────────────

    def _review_path(self, rec_id: str) -> str:
        return os.path.join(self._review_dir, f"{rec_id}.json")